### ISSUE TITLE
mvn clean package errors with package does not exist

### ISSUE THREAD

**Issue by gjensen2015** [coconut2015/cookcc#33]
I added the plugin per your directions, and it worked fine, but when I added additional dependencies to the code (like slf4j and  gson) the package command would error with "error: package org.slf4j does not exist"

mvn would generate the code, so I was able to do a refresh in eclipse and see the changes and even run it, but I need it to build from the command line. Is this a known issue or is my pom set up incorrectly?

**Comment by coconut2015** [comment]
It is your pom's issue.  Cookcc does not depend on slf4j etc.

**Comment by gjensen2015** [comment]
I don't think I made myself clear. I am not saying Cookcc depends on slf4j.  As I previously stated, I was able to get everything working initially. The problem arises from the fact I can't  do what I need without external dependencies. 

The long story is I am trying to write a grammar used to filter Json objects. My initial version just used a HashMap, so there were no other dependencies. Cookcc worked as advertised, and once I got my head around how things worked, it made coding very easy. After I reworked it to use Gson objects, I started having problems.  I have modified the plugins dependency section to add Gson, but that didn't help.  The slf4j dependency is for the logging I added to my Rules for debugging. I could do with out, but  without Gson, I have nothing.

I haven't dived into the plugin code, but I think the problem stems from the fact you are compiling the code, even though it part of the generate-sources phase.

So, my question is, is it possible to write Rules in Java, that have  external dependencies, and can be built as part of a larger project that uses Maven. If so, can you point me to an example. Your help would be much appreciated. If, not, do you have any suggestions on alternatives?
Thanks

**Comment by coconut2015** [comment]
I somewhat see the problem, but I wish you did not use an issue as a place to get help.  You could've used the discussion group asking the problem and provide more information.

I am assuming that you are using the CookCC Maven plugin.  This plugin basically uses a simpler approach to construct the command line execution needed to launch Java compiler.  This is not considering any additional libraries that you may need to compile your Java program, since in general you should not.  If you want to load the libraries, then you would have to either construct an ant script or build a command script yourself.  I added this plugin mostly for experienced people who can generally get lexer / parser right easily, since a lot of warnings / errors may be not be actually captured (known issue of launching Java C compiler via Maven), and have an automated way of re-generate the code when needed.

But in general, you should avoid having external dependencies when you write lexers / parsers.  Doing logging should be done on the final object / objects generated, instead of every single token you saw.  You want to be able to unit test this thing easily without any baggages.  I am assuming that you were trying to debug.  But that is not the way to do the debugging.  Lexer / parser should be tested with lightest possible dependencies.  Since you will need to have tons of separate unit tests with various inputs to test your grammar.

A simpler way of thinking about is to separate the actual interpreter (i.e. handler of tokens, rules) from the parsing itself.  This also separates the dependencies needed.
